### ISSUE TITLE
mv: cannot stat 'temp.geojson': No such file or directory

### ISSUE THREAD

**Issue by lgblkb** [Faranio/Crop_Field_Segmentation#2]
12:37:13 DEBUG | | cmd: potrace -b geojson /nfs/storage/caches/Crop_Field_Segmentation/S2B_MSIL2A_20190824T081609_N0213_R121_T37UGU_20190824T125652.SAFE/Masks/32_13.bmp -o /nfs/storage/caches/Crop_Field_Segmentation/S2B_MSIL2A_20190824T081609_N0213_R121_T37UGU_20190824T125652.SAFE/Masks/32_13.geojson && cat /nfs/storage/caches/Crop_Field_Segmentation/S2B_MSIL2A_20190824T081609_N0213_R121_T37UGU_20190824T125652.SAFE/Masks/32_13.geojson | simplify-geojson -t 5 > temp.geojson && mv temp.geojson /nfs/storage/caches/Crop_Field_Segmentation/S2B_MSIL2A_20190824T081609_N0213_R121_T37UGU_20190824T125652.SAFE/Masks/32_13.geojson

mv: cannot stat 'temp.geojson': No such file or directory

[2020-09-29 12:37:15,848: ERROR/ForkPoolWorker-2] Task image_segmentor[d3b91ca5-49f6-4f99-a71f-7f1327782888] raised unexpected: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/egistic_db/egistic/crop_field_segmentation/app/celery_tasks.py", line 61, in image_segmentor
    return segment_safe_product(safe_folder_path, roi_wkt)
  File "/opt/venv/lib/python3.8/site-packages/lgblkb_tools/logify.py", line 121, in wrapper
    out = wrapped(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 1859, in wrapper
    result = func(*args, **kwargs)
  File "/home/egistic_db/egistic/crop_field_segmentation/app/pipeline.py", line 344, in segment_safe_product
    perform_modifications(mask_info,
  File "/opt/venv/lib/python3.8/site-packages/lgblkb_tools/logify.py", line 121, in wrapper
    out = wrapped(*args, **kwargs)
  File "/home/egistic_db/egistic/crop_field_segmentation/app/pipeline.py", line 253, in perform_modifications
    shp_file = json.load(file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Faranio** [comment]
**(RESOLVED)**

_Explanation:_

This bug happened due to empty geometries being passed to bash commands such as potrace, simplify-geojson, etc. 

_Solution:_

Check whether the file exists and is not empty.
