### ISSUE TITLE
Crop_field_segmentation Celery Worker Error (JSON.decoder.JSONDecodeError)

### ISSUE THREAD

**Issue by Faranio** [Faranio/Crop_Field_Segmentation#3]
[2020-09-29 12:37:15,866: ERROR/ForkPoolWorker-1] Task crop_field_segmentation[59c5149d-840b-4edf-bfd8-efb3ac8c41f1] raised unexpected: Exception("<class 'json.decoder.JSONDecodeError'>(['Expecting value: line 1 column 1 (char 0)'])")

Traceback (most recent call last):

  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__

    return self.run(*args, **kwargs)

  File "/home/egistic_db/egistic/crop_field_segmentation/app/celery_tasks.py", line 29, in crop_field_segmentation

    multipolygons = celery.group(

  File "/opt/venv/lib/python3.8/site-packages/celery/result.py", line 708, in get

    return (self.join_native if self.supports_native_join else self.join)(

  File "/opt/venv/lib/python3.8/site-packages/celery/result.py", line 839, in join_native

    raise value

Exception: <class 'json.decoder.JSONDecodeError'>(['Expecting value: line 1 column 1 (char 0)'])

**Comment by lgblkb** [comment]
@Faranio Due to how celery.group works (unfortunately), when single task in a group fails, the whole group fails. The error you posted is coming from a parent task that called celery.group. You should instead inspect the logs of `image_segmentor` task to see the root cause of the error.

The child task's (`image_segmentor`) log:


mv: cannot stat 'temp.geojson': No such file or directory
[2020-09-29 12:37:15,848: ERROR/ForkPoolWorker-2] Task image_segmentor[d3b91ca5-49f6-4f99-a71f-7f1327782888] raised unexpected: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):


  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task


    R = retval = fun(*args, **kwargs)


  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__


    return self.run(*args, **kwargs)


  File "/home/egistic_db/egistic/crop_field_segmentation/app/celery_tasks.py", line 61, in image_segmentor


    return segment_safe_product(safe_folder_path, roi_wkt)


  File "/opt/venv/lib/python3.8/site-packages/lgblkb_tools/logify.py", line 121, in wrapper


    out = wrapped(*args, **kwargs)


  File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 1859, in wrapper


    result = func(*args, **kwargs)


  File "/home/egistic_db/egistic/crop_field_segmentation/app/pipeline.py", line 344, in segment_safe_product


    perform_modifications(mask_info,


  File "/opt/venv/lib/python3.8/site-packages/lgblkb_tools/logify.py", line 121, in wrapper


    out = wrapped(*args, **kwargs)


  File "/home/egistic_db/egistic/crop_field_segmentation/app/pipeline.py", line 253, in perform_modifications


    shp_file = json.load(file)


  File "/usr/lib/python3.8/json/__init__.py", line 293, in load


    return loads(fp.read(),


  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads


    return _default_decoder.decode(s)


  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode


    obj, end = self.raw_decode(s, idx=_w(s, 0).end())


  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode


    raise JSONDecodeError("Expecting value", s, err.value) from None


json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lgblkb** [comment]
So, the error is coming from `shp_file = json.load(file)` line. Maybe the `mv: cannot stat 'temp.geojson': No such file or directory` line might give some clues?

**Comment by Faranio** [comment]
I have changed the code a bit regarding this issue and now I am checking it with new requets from Rauan.
