### ISSUE TITLE
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. 

### ISSUE THREAD

**Issue by Faranio** [Faranio/Crop_Field_Segmentation#4]
[2020-09-29 23:49:04,714: ERROR/ForkPoolWorker-1] Task crop_field_segmentation[7670d3ca-86ed-4e9c-b4dc-3cf1ce64a921] raised unexpected: TopologicalError("The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f812b9a4e80>")

Traceback (most recent call last):

  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__

    return self.run(*args, **kwargs)

  File "/home/egistic_db/egistic/crop_field_segmentation/app/celery_tasks.py", line 40, in crop_field_segmentation

    out = shg.MultiPolygon(remove_overlaps(multipolygons.reset_index(drop=True).geometry, []))

  File "/home/egistic_db/egistic/crop_field_segmentation/app/pipeline.py", line 269, in remove_overlaps

    area = polygon.intersection(check).area

  File "/opt/venv/lib/python3.8/site-packages/shapely/geometry/base.py", line 676, in intersection

    return geom_factory(self.impl['intersection'](self, other))

  File "/opt/venv/lib/python3.8/site-packages/shapely/topology.py", line 70, in __call__

    self._check_topology(err, this, other)

  File "/opt/venv/lib/python3.8/site-packages/shapely/topology.py", line 35, in _check_topology

    raise TopologicalError(

shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f812b9a4e80>

**Comment by lgblkb** [comment]
@Faranio Once I was trying to combat this kind of errors by randomly shifting the polygon vertices by tiny distances. Refer to the code below.
P.S. This code is not doing the shiftings properly because all the vertices are moved to the same tiny distance. A better approach would be to move each vertex by random distances/directions.

```
    @staticmethod
    def _make_difference(g1, g2, max_tries=100):
        try_count = 0
        while try_count < max_tries:
            try_count += 1
            try:
                res = g1.difference(g2)
                # logger.debug('res: %s',res)
                return res.iloc[0]
            except shapely.errors.TopologicalError:
                if not isinstance(g2, shg.MultiPolygon): raise ValueError
                g2: shg.MultiPolygon = g2
                out_polys = list()
                for poly in g2:
                    poly: shg.Polygon = poly
                    out_poly = ThePoly(ThePoly(poly).xy + np.random.rand() * 1e-6).geometry
                    for interior in poly.interiors:
                        logger.debug('interior: %s', interior)
                        out_poly = out_poly.difference(shg.Polygon(interior))

                    out_polys.append(out_poly)
                out_multipolygon = shg.MultiPolygon(out_polys)
                return out_multipolygon
        # logger.debug('type(g2): %s',type(g2))
        # for g2.exterior
        # g2=shaff.scale(g2,xfact=1+np.random.rand()*1e-3*(try_count+1),yfact=1+np.random.rand()*1e-3*(try_count+1))
        raise NotImplementedError
```
